language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g karma-phantomjs-launcher
  - npm install -g gulp
script:
  - gulp test_ci
after_success:
  - npm uninstall -g karma-phantomjs-launcher
  - npm uninstall -g gulp
